FROM openjdk:11.0.16-jre-slim-buster
WORKDIR /etc/build
ARG JAR_FILE_PATH=/var/jenkins_home/workspace/'Movigation BE'/backend/build/libs
COPY ${JAR_FILE_PATH}/movigation-0.0.1-SNAPSHOT.jar /etc/build
CMD java -jar movigation-0.0.1-SNAPSHOT.jar
