-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 21:35:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema movigation_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movigation_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movigation_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `movigation_db` ;

-- -----------------------------------------------------
-- Table `movigation_db`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movigation_db`.`movies` (
  `tmdb_movie_id` INT NOT NULL,
  `movie_name` VARCHAR(100) NULL DEFAULT NULL,
  `poster_path` VARCHAR(100) NULL DEFAULT NULL,
  `vote_average` FLOAT NULL DEFAULT NULL,
  `overview` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`tmdb_movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movigation_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movigation_db`.`users` (
  `user_index` INT NOT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `nickname` VARCHAR(10) NULL DEFAULT NULL,
  `profile_image` VARCHAR(100) NULL DEFAULT NULL,
  `phone_number` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`user_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movigation_db`.`dislike_movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movigation_db`.`dislike_movies` (
  `user_index` INT NOT NULL,
  `tmdb_movie_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_index`),
  INDEX `fk_Dislike_Movies_Movies1_idx` (`tmdb_movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_dislike_movies_movies`
    FOREIGN KEY (`tmdb_movie_id`)
    REFERENCES `movigation_db`.`movies` (`tmdb_movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dislike_movies_users`
    FOREIGN KEY (`user_index`)
    REFERENCES `movigation_db`.`users` (`user_index`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movigation_db`.`like_movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movigation_db`.`like_movies` (
  `user_index` INT NOT NULL,
  `tmdb_movie_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_index`),
  INDEX `fk_Like_Movies_Movies1_idx` (`tmdb_movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_movies_movies`
    FOREIGN KEY (`tmdb_movie_id`)
    REFERENCES `movigation_db`.`movies` (`tmdb_movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_like_movies_users`
    FOREIGN KEY (`user_index`)
    REFERENCES `movigation_db`.`users` (`user_index`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movigation_db`.`like_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movigation_db`.`like_genres` (
  `user_index` INT NOT NULL,
  `genre_number` INT NULL DEFAULT NULL,
  `tmdb_genre_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_index`),
  INDEX `fk_LikeGenres_Genre1_idx` (`genre_number` ASC, `tmdb_genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_genres_genre`
    FOREIGN KEY (`genre_number` , `tmdb_genre_id`)
    REFERENCES `movigation_db`.`genres` (`genre_id` , `tmdb_genre_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_like_genres_user`
    FOREIGN KEY (`user_index`)
    REFERENCES `movigation_db`.`users` (`user_index`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movigation_db`.`movies_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movigation_db`.`movies_genres` (
  `tmdb_movie_id` INT NOT NULL,
  `genre_number` INT NOT NULL,
  `tmdb_genre_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`tmdb_movie_id`, `genre_number`),
  INDEX `fk_movies_genres_genres` (`tmdb_genre_id` ASC) VISIBLE,
  INDEX `fk_movies_genres_like_genres1_idx` (`genre_number` ASC) VISIBLE,
  CONSTRAINT `fk_movies_genres_genres`
    FOREIGN KEY (`tmdb_genre_id`)
    REFERENCES `movigation_db`.`genres` (`tmdb_genre_id`),
  CONSTRAINT `fk_movies_genres_movies`
    FOREIGN KEY (`tmdb_movie_id`)
    REFERENCES `movigation_db`.`movies` (`tmdb_movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movies_genres_like_genres`
    FOREIGN KEY (`genre_number`)
    REFERENCES `movigation_db`.`like_genres` (`genre_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movigation_db`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movigation_db`.`reviews` (
  `review_index` INT NOT NULL,
  `tmdb_movie_id` INT NULL DEFAULT NULL,
  `user_index` INT NULL DEFAULT NULL,
  `nickname` VARCHAR(10) NULL DEFAULT NULL,
  `review_context` VARCHAR(500) NULL DEFAULT NULL,
  `score` INT NULL DEFAULT NULL,
  PRIMARY KEY (`review_index`),
  INDEX `fk_Review_User_idx` (`user_index` ASC) VISIBLE,
  INDEX `fk_Review_Movie1_idx` (`tmdb_movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_movie`
    FOREIGN KEY (`tmdb_movie_id`)
    REFERENCES `movigation_db`.`movies` (`tmdb_movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_review_user`
    FOREIGN KEY (`user_index`)
    REFERENCES `movigation_db`.`users` (`user_index`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
